[versions]
espressoCore="3.6.1"
junit="4.13.2"
junitVersion="1.2.1"
kotlin="2.1.0"
androidGradlePlugin="8.7.3"
okhttp="5.0.0-alpha.14"
okio="3.9.1"
recyclerview="1.3.2"
[libraries]
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
junit = { module = "junit:junit", version.ref = "junit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-dnsoverhttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp" }
okio={module="com.squareup.okio:okio" ,version.ref="okio"}

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

androidx-benchmark = {id="androidx.benchmark",version="1.3.3"}

kotlin-android = {id="org.jetbrains.kotlin.android",version.ref="kotlin"}
